# Basic Information 
title: Haoxiang Wang
position: PhD Candidate
affiliation: Automation, Tsinghua University
affiliation_link: https://www.tsinghua.edu.cn/
# affiliation_logo: ./assets/img/illinois.svg
email: whx22@mails.tsinghua.edu.cn

# Search Engine Optimization (SEO)
keywords: haoxiang wang, wang haoxiang, haoxiangwang, wanghaoxiang
canonical: https://qingxu-thu.github.io
description: Haoxiang Wang is a PhD Candidate at the Department of Automation, Tsinghua University. His research interests are physical simulation and animation.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=HGhm8g0AAAAJ&hl=en
github_link: https://github.com/qingxu-thu/


# Images 
avatar: ./assets/img/TSG-00656-2020-haoxiangwang.jpg

# Footnotes
footnote: Personal academic homepage.
footnote_link: https://github.com/qingxu-thu/

# Analytics
# clustrmaps_id: YOUR_CLUSTRMAPS_ID

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
